# Generated by Django 6.0.7 on 2026-08-21 09:24

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('school', models.CharField(max_length=150)),
                ('school_code', models.CharField(max_length=20)),
                ('faculty', models.CharField(max_length=150)),
                ('faculty_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EbaIncrease',
            fields=[
                ('year', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('multiplier', models.DecimalField(decimal_places=6, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='IncrementCap',
            fields=[
                ('level', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('max_steps', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.department')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OnCostRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_cost_type', models.CharField(choices=[('superannuation', 'Superannuation'), ('payroll_tax', 'Payroll Tax'), ('workcover', 'WorkCover'), ('leave_loading', 'Leave Loading'), ('long_service_leave', 'Long Service Leave'), ('parental_leave', 'Parental Leave'), ('annual_leave_provision', 'Annual Leave Provision')], max_length=32)),
                ('employment_type', models.CharField(blank=True, choices=[('Continuing', 'Continuing'), ('Fixed-Term', 'Fixed-Term'), ('Casual', 'Casual')], max_length=20, null=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rate', models.DecimalField(decimal_places=4, help_text='Proportion, not percentage. E.g 0.1200 means 12%', max_digits=6)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('on_cost_type', 'employment_type', 'year'), name='unique_on_cost_rate', nulls_distinct=False)],
            },
        ),
        migrations.CreateModel(
            name='SalaryRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_type', models.CharField(choices=[('Fortnight', 'Fortnight'), ('Casual', 'Casual')], max_length=20)),
                ('category', models.CharField(choices=[('Academic', 'Academic'), ('Professional', 'Professional')], max_length=20)),
                ('classification', models.CharField(max_length=20)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=12)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('payroll_type', 'category', 'classification'), name='unique_salary_rate')],
            },
        ),
    ]
