# Generated by Django 6.0.7 on 2026-08-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_calculationconstant_minimumcostrecoverymultiplier_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryRateMultiplier",
            fields=[
                (
                    "time_basis",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("multiplier", models.DecimalField(decimal_places=10, max_digits=12)),
            ],
        ),
    ]
