# Generated by Django 6.0.7 on 2026-08-28 11:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_nonstaffcostline_yearamount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverableType',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RevenueCategory',
            fields=[
                ('budget_ledger_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('external_party', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='budget',
            name='cash_co_contribution',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='budget',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='department',
            name='budget_unit',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='nonstaffcostline',
            name='category',
            field=models.ForeignKey(default=5060, on_delete=django.db.models.deletion.PROTECT, to='api.nonstaffcostcategory'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('description', models.CharField(max_length=200)),
                ('invoice_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('due_date', models.CharField(blank=True, max_length=100)),
                ('dependency', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sponsor', models.CharField(blank=True, max_length=100)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='api.budget')),
                ('deliverable_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.deliverabletype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('budget', 'number'), name='unique_deliverable_number')],
            },
        ),
    ]
