# Generated by Django 6.0.7 on 2026-09-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_deliverabletype_revenuecategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="dean_exemption_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="budget",
            name="justification",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="budget",
            name="justification_notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
