# Generated by Django 6.0.7 on 2026-09-07 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_budget_approval_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='other_funder',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='other_funder_category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
