# Generated by Django 6.0.7 on 2026-09-07 03:32

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_project_other_funder_project_other_funder_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="margin",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.30"), max_digits=5
            ),
        ),
    ]
