# Generated by Django 6.0.7 on 2026-09-07 13:28

from django.db import migrations, models


def delete_payroll_tax_rates(apps, schema_editor):
    apps.get_model("api", "OnCostRate").objects.filter(
        on_cost_type="payroll_tax"
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_budget_margin"),
    ]

    operations = [
        migrations.RunPython(
            delete_payroll_tax_rates,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="oncostrate",
            name="on_cost_type",
            field=models.CharField(
                choices=[
                    ("superannuation", "Superannuation"),
                    ("workcover", "WorkCover"),
                    ("leave_loading", "Leave Loading"),
                    ("long_service_leave", "Long Service Leave"),
                    ("parental_leave", "Parental Leave"),
                    ("annual_leave_provision", "Annual Leave Provision"),
                ],
                max_length=32,
            ),
        ),
    ]
