# Generated by Django 6.0.7 on 2026-09-08 18:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_payroll_tax_on_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='cash_co_contribution',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='budget',
            name='cost_multiplier',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='budget',
            name='in_kind_multiplier',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='budget',
            name='margin',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.30'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='invoice_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='ebaincrease',
            name='multiplier',
            field=models.DecimalField(decimal_places=6, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='minimumcostrecoverymultiplier',
            name='multiplier',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='nonstaffcostline',
            name='indirect_rate_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='oncostrate',
            name='rate',
            field=models.DecimalField(decimal_places=4, help_text='Proportion, not percentage. E.g 0.1200 means 12%', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_month',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_month',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='salaryrate',
            name='rate',
            field=models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='salaryratemultiplier',
            name='multiplier',
            field=models.DecimalField(decimal_places=18, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='yearallocation',
            name='time',
            field=models.DecimalField(decimal_places=4, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='yearamount',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
