# Generated by Django 6.0.7 on 2026-09-17 05:58

from decimal import Decimal

from django.db import migrations, models

from api.models import build_reference


def backfill_references(apps, schema_editor):
    # Projects that predate the column. Same shape as the one save() allocates,
    # so nothing has to know which era a project came from.
    Project = apps.get_model("api", "Project")
    for project in Project.objects.filter(reference__isnull=True):
        project.reference = build_reference(project.created_at.year, project.pk)
        project.save(update_fields=["reference"])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_budget_cash_co_contribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='total_price_exc_gst',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='project',
            name='reference',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(
            backfill_references,
            migrations.RunPython.noop,
        ),
    ]
