# Generated by Django 6.0.7 on 2026-09-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_budget_total_price_exc_gst_project_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='funder',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
