# Generated by Django 6.0.7 on 2026-09-17 09:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_project_title_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='margin',
            field=models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
