# Generated by Django 6.0.7 on 2026-09-18 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_budget_margin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('hod_review', 'Head of Department review'), ('dean_review', 'Dean review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('department', 'Head of Department'), ('faculty', 'Dean')], max_length=20)),
                ('required', models.BooleanField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('not_required', 'Not required')], default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='api.budget')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('budget', 'level'), name='unique_approval_step_per_level'), models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['approved', 'rejected']), _negated=True), models.Q(('decided_at__isnull', False), ('decided_by__isnull', False)), _connector='OR'), name='decided_approval_step_names_its_decider'), models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['pending', 'not_required']), _negated=True), models.Q(('decided_at__isnull', True), ('decided_by__isnull', True)), _connector='OR'), name='undecided_approval_step_names_nobody')],
            },
        ),
    ]
