# Generated by Django 6.0.7 on 2026-09-21 14:20

import api.models
from django.db import migrations, models
from django.db.models.functions import Lower


def fill_blank_emails(apps, schema_editor):
    """
    Email is about to become unique, and AbstractUser let it be blank.

    Two blank strings collide, so anyone without one is given a placeholder
    derived from the username they signed in with, or from their id. There are
    no such accounts in production, which has no users at all yet, but a
    developer database may hold one from createsuperuser.
    """
    User = apps.get_model("api", "User")
    for user in User.objects.filter(email="").only("id", "username"):
        handle = (user.username or f"user{user.id}").strip()
        User.objects.filter(pk=user.pk).update(email=f"{handle}@invalid.local")


def lowercase_emails(apps, schema_editor):
    """
    Fold existing addresses down before a case-insensitive unique index.

    Sign-in matches case-insensitively, so two rows differing only by case
    would be indistinguishable to it. Production has no users yet; in a
    developer database such a pair would surface here as a constraint error,
    which is the right place to find out.
    """
    User = apps.get_model("api", "User")
    for user in User.objects.exclude(email="").only("id", "email"):
        lowered = user.email.lower()
        if lowered != user.email:
            User.objects.filter(pk=user.pk).update(email=lowered)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_seed_groups'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', api.models.UserManager()),
            ],
        ),
        # Before username goes, since the backfill reads it.
        migrations.RunPython(fill_blank_emails, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.RunPython(lowercase_emails, migrations.RunPython.noop),
        # unique=True above is case-sensitive, which is not what signing in
        # does. This is what makes one address mean one account.
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(
                Lower('email'), name='user_email_unique_ci'
            ),
        ),
    ]
