# Generated by Django 6.0.7 on 2026-09-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_user_signs_in_by_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonstaffcostline',
            name='in_kind_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='staffcostline',
            name='in_kind_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddConstraint(
            model_name='nonstaffcostline',
            constraint=models.CheckConstraint(condition=models.Q(('in_kind', True), ('in_kind_reason', ''), _connector='OR'), name='nonstaffcostline_reason_needs_the_tick'),
        ),
        migrations.AddConstraint(
            model_name='staffcostline',
            constraint=models.CheckConstraint(condition=models.Q(('in_kind', True), ('in_kind_reason', ''), _connector='OR'), name='staffcostline_reason_needs_the_tick'),
        ),
    ]
