# Generated by Django 6.0.7 on 2026-09-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_project_owner_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalstep',
            name='required',
        ),
    ]
