# Generated by Django 6.0.7 on 2026-09-25 16:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_approvalstep_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='total_price_exc_gst',
        ),
        migrations.AddField(
            model_name='budget',
            name='dean_triggers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='budget',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='total_price_inc_gst',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
    ]
