# Generated by Django 6.0.7 on 2026-09-26 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_budget_total_price_exc_gst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='cloned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='api.budget'),
        ),
    ]
