# Generated by Django 6.0.7 on 2026-09-30 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_cost_line_uuid_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonstaffcostcategory',
            name='excludes_additional_rate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nonstaffcostcategory',
            name='version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.lookupversion'),
            preserve_default=False,
        ),
    ]
