# Generated by Django 6.0.7 on 2026-09-30 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_ebaincrease_multiplier_ebaincrease_rate_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ebaincrease',
            name='unique_eba_increase',
        ),
        migrations.AlterField(
            model_name='ebaincrease',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='ebaincrease',
            constraint=models.UniqueConstraint(fields=('year', 'version'), name='unique_eba'),
        ),
    ]
