# Generated by Django 6.0.7 on 2026-10-01 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_retire_in_kind_multiplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupChangeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('change_count', models.PositiveIntegerField()),
                ('saved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_sets', to='api.lookupversion')),
            ],
        ),
    ]
