# Generated by Django 6.0.7 on 2026-10-02 02:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_project_starts_empty'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='currency',
            field=models.CharField(default='AUD', max_length=3),
        ),
        migrations.AddField(
            model_name='budget',
            name='exchange_rate_override',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))]),
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=60)),
                ('rate', models.DecimalField(decimal_places=6, help_text='How much of this currency 1 AUD buys.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.lookupversion')),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'constraints': [models.UniqueConstraint(fields=('code', 'version'), name='unique_currency')],
            },
        ),
    ]
