# Generated by Django 6.0.7 on 2026-10-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_increment_cap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryrate',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='salaryrate',
            name='payroll_type',
            field=models.CharField(choices=[('Fortnight', 'Fortnight'), ('Fortnight', 'Fortnight'), ('Casual', 'Casual')], max_length=20),
        ),
        migrations.AlterField(
            model_name='staffcostline',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
