# Generated by Django 6.0.7 on 2026-10-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_increment_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='approved_figures',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
