# Generated by Django 6.0.7 on 2026-10-04 10:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_budget_approved_figures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='margin',
            field=models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'), message="A margin can't be below 0%%."), django.core.validators.MaxValueValidator(Decimal('9.9999'), message='A margin can be at most 999.99%%.')]),
        ),
    ]
