# Generated by Django 6.0.7 on 2026-10-04 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_margin_bounds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonstaffcostline',
            name='indirect_rate_multiplier',
        ),
    ]
