# Generated by Django 6.0.7 on 2026-10-04 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_salaryrate_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='mode',
        ),
    ]
