# Generated by Django 6.0.7 on 2026-10-05 06:26

from django.db import migrations, models


def delete_members(apps, schema_editor):
    apps.get_model("api", "UserOrgAssignment").objects.filter(role="member").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_remove_budget_mode'),
    ]

    operations = [
        migrations.RunPython(delete_members, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='userorgassignment',
            name='org_assignment_scope_matches_role',
        ),
        migrations.AlterField(
            model_name='userorgassignment',
            name='role',
            field=models.CharField(choices=[('hod', 'Head of Department'), ('dean', 'Dean')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='userorgassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('department__isnull', False), ('faculty__isnull', True), ('role', 'hod')), models.Q(('department__isnull', True), ('faculty__isnull', False), ('role', 'dean')), _connector='OR'), name='org_assignment_scope_matches_role'),
        ),
    ]
