/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/budgets/{budget_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["root_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["root_partial_update"];
        trace?: never;
    };
    "/api/budgets/{budget_id}/deliverables/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deliverables_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/budgets/{budget_id}/deliverables/{deliverable_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deliverables_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/budgets/{budget_id}/non-staff-lines/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["non_staff_lines_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/budgets/{budget_id}/non-staff-lines/{line_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["non_staff_lines_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/budgets/{budget_id}/staff-lines/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["staff_lines_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/budgets/{budget_id}/staff-lines/{line_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["staff_lines_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BudgetDetail: {
            project_info: components["schemas"]["ProjectInfo"];
            budget_info: components["schemas"]["BudgetInfo"];
            years: number[];
            staff_cost: components["schemas"]["StaffCost"];
            staff_in_kind_cost: components["schemas"]["StaffCost"];
            non_staff_cost: components["schemas"]["NonStaffCost"];
            non_staff_in_kind_cost: components["schemas"]["NonStaffCost"];
            budget_summary: components["schemas"]["BudgetSummary"];
        };
        BudgetInfo: {
            mode: string;
            /** Format: double */
            cost_multiplier: number;
            /** Format: double */
            in_kind_multiplier: number;
            gst_applicable: boolean;
            /** Format: double */
            cash_co_contribution: number;
            comments: string;
            status: string;
            deliverables: components["schemas"]["DeliverableResult"][];
        };
        BudgetSummary: {
            price_summary: components["schemas"]["PriceSummary"];
            staff_budget: components["schemas"]["StaffBudget"];
            non_staff_budget: components["schemas"]["NonStaffBudget"];
            in_kind_costs: components["schemas"]["InKindCosts"];
        };
        /**
         * @description * `Academic` - Academic
         *     * `Professional` - Professional
         * @enum {string}
         */
        CategoryEnum: "Academic" | "Professional";
        Deliverable: {
            number: number;
            description: string;
            deliverable_type: string;
            /** Format: double */
            invoice_amount?: number | null;
            due_date?: string;
            dependency?: number | null;
            sponsor?: string;
        };
        DeliverableResult: {
            number: number;
            description: string;
            deliverable_type: string;
            /** Format: double */
            invoice_amount: number | null;
            due_date: string;
            dependency: number | null;
            sponsor: string;
        };
        /**
         * @description * `Continuing` - Continuing
         *     * `Fixed-Term` - Fixed-Term
         *     * `Casual` - Casual
         * @enum {string}
         */
        EmploymentTypeEnum: "Continuing" | "Fixed-Term" | "Casual";
        InKindCosts: {
            in_kind_staff_budget: components["schemas"]["StaffBudget"];
            in_kind_non_staff_budget: components["schemas"]["NonStaffBudget"];
            /** Format: double */
            total_in_kind_costs: number;
        };
        NonStaffBudget: {
            category_totals: {
                [key: string]: number;
            };
            /** Format: double */
            direct_total: number;
            /** Format: double */
            indirect_cost_recovery: number;
            /** Format: double */
            total_non_staff_costs: number;
        };
        NonStaffCost: {
            lines: components["schemas"]["NonStaffLine"][];
            direct_total: components["schemas"]["NonStaffTotal"];
            indirect_total: components["schemas"]["NonStaffTotal"];
            column_total: components["schemas"]["NonStaffTotal"];
        };
        NonStaffLine: {
            id: number;
            cost_group: string;
            expense_type: string;
            description: string;
            in_kind: boolean;
            add_ten_percent: boolean;
            /** Format: double */
            indirect_rate_multiplier: number | null;
            by_year: components["schemas"]["NonStaffYear"][];
            /** Format: double */
            total: number;
            /** Format: double */
            direct_total: number;
        };
        NonStaffLineInput: {
            cost_group: string;
            expense_type: string;
            description?: string;
            /** @default false */
            in_kind: boolean;
            /** @default false */
            add_ten_percent: boolean;
            /** Format: double */
            indirect_rate_multiplier?: number | null;
            amounts?: components["schemas"]["YearAmount"][];
        };
        NonStaffTotal: {
            by_year: components["schemas"]["NonStaffTotalYear"][];
            /** Format: double */
            total: number;
        };
        NonStaffTotalYear: {
            year: number;
            /** Format: double */
            cost: number;
        };
        NonStaffYear: {
            year: number;
            /** Format: double */
            amount: number;
        };
        PatchedBudgetUpdate: {
            section?: components["schemas"]["SectionEnum"];
            row_id?: number | null;
            field?: string;
            value?: unknown;
        };
        PriceSummary: {
            /** Format: double */
            staff_cost: number;
            /** Format: double */
            non_staff_cost: number;
            /** Format: double */
            project_cost: number;
            /** Format: double */
            in_kind_staff_cost: number;
            /** Format: double */
            in_kind_non_staff_cost: number;
            /** Format: double */
            in_kind_project_cost: number;
            /** Format: double */
            staff_cost_percentage: number;
            /** Format: double */
            non_staff_cost_percentage: number;
            /** Format: double */
            total_project_cost: number;
            /** Format: double */
            total_price_exc_gst: number;
            /** Format: double */
            total_price_inc_gst: number;
            /** Format: double */
            cash_benefit: number;
            /** Format: double */
            total_in_kind_contribution: number;
            /** Format: double */
            total_cash_co_contribution: number;
            /** Format: double */
            university_position: number;
        };
        ProjectInfo: {
            title: string;
            chief_investigator: string;
            funder: string;
            department: string;
            faculty: string;
            scheme: string;
            start_year: number;
            start_month: number;
            end_year: number;
            end_month: number;
            company: string;
            cost_centre: string;
            activity: string | null;
            region: string | null;
            additional_information: string;
        };
        /**
         * @description * `project` - project
         *     * `budget` - budget
         *     * `staff` - staff
         *     * `non_staff` - non_staff
         * @enum {string}
         */
        SectionEnum: "project" | "budget" | "staff" | "non_staff";
        StaffBudget: {
            category_totals: {
                [key: string]: number;
            };
            /** Format: double */
            cost_before_recovery: number;
            /** Format: double */
            cost_recovery: number;
            /** Format: double */
            cost_recovery_multiplier: number;
            /** Format: double */
            total_staff_costs: number;
        };
        StaffCost: {
            lines: components["schemas"]["StaffLine"][];
            column_total: components["schemas"]["StaffTotal"];
        };
        StaffLine: {
            id: number;
            name_role: string;
            employment_type: string;
            category: string;
            classification: string;
            time_basis: string;
            in_kind: boolean;
            /** Format: double */
            rate_2025: number;
            by_year: components["schemas"]["StaffYear"][];
            /** Format: double */
            total: number;
        };
        StaffLineInput: {
            name_role: string;
            employment_type: components["schemas"]["EmploymentTypeEnum"];
            category: components["schemas"]["CategoryEnum"];
            classification: string;
            time_basis: components["schemas"]["TimeBasisEnum"];
            /** @default false */
            in_kind: boolean;
            allocations?: components["schemas"]["YearAllocation"][];
        };
        StaffTotal: {
            by_year: components["schemas"]["StaffTotalYear"][];
            /** Format: double */
            total: number;
        };
        StaffTotalYear: {
            year: number;
            /** Format: double */
            cost: number;
        };
        StaffYear: {
            year: number;
            /** Format: double */
            time: number;
            /** Format: double */
            cost: number;
        };
        /**
         * @description * `FTE` - FTE
         *     * `Daily` - Daily
         *     * `Hourly` - Hourly
         * @enum {string}
         */
        TimeBasisEnum: "FTE" | "Daily" | "Hourly";
        YearAllocation: {
            year: number;
            /** Format: double */
            time: number;
        };
        YearAmount: {
            year: number;
            /** Format: double */
            amount: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                budget_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetDetail"];
                };
            };
        };
    };
    root_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                budget_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedBudgetUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedBudgetUpdate"];
                "multipart/form-data": components["schemas"]["PatchedBudgetUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetDetail"];
                };
            };
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deliverables_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                budget_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Deliverable"];
                "application/x-www-form-urlencoded": components["schemas"]["Deliverable"];
                "multipart/form-data": components["schemas"]["Deliverable"];
            };
        };
        responses: {
            /** @description No response body */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deliverables_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                budget_id: number;
                deliverable_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    non_staff_lines_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                budget_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NonStaffLineInput"];
                "application/x-www-form-urlencoded": components["schemas"]["NonStaffLineInput"];
                "multipart/form-data": components["schemas"]["NonStaffLineInput"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetDetail"];
                };
            };
        };
    };
    non_staff_lines_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                budget_id: number;
                line_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    staff_lines_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                budget_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffLineInput"];
                "application/x-www-form-urlencoded": components["schemas"]["StaffLineInput"];
                "multipart/form-data": components["schemas"]["StaffLineInput"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetDetail"];
                };
            };
        };
    };
    staff_lines_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                budget_id: number;
                line_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
